# This is the workflow name
name: AWS Databricks Terraform Infrastructure deployment (test)

# This is optional. Name for the workflow runs
run-name: ${{ github.actor }} is learning GitHub Actions

#Event trigger for this workflow
on:
  push:
    branches: 
      - main

jobs:

# The Job ID
  deploying_aws_databricks:
    name: Deploy Databricks on AWS with Terraform   # This is the job name
    runs_on: ubuntu-latest   # Runner where the job is being run. In this case, a GitHub-hosted Linux runner
    #strategy:
      #max-parallel: 4
    environment: AWS # This is the environment that the job is referencing. All deployment protection rules must pass before a job referencing the environment is sent to a runner
    #defaults:
      #run:
        #working-directory: ./scripts
    steps:

      - uses: actions/checkout@v4 # Checks out your repository into the runner allowing you to run scripts or other actions against your code 
      
    
